### PR TITLE
Fix for #1 - Intercepts filenames on HtmlReporter to truncate if length > 255

### LINKED ISSUE #1: Throws error ENAMETOOLONG
Hi @samccone,

First of all, thanks for this tool :) Nice job, really appreciate it. And thanks for the awesome #perfmatters work you've been doing, you guys are awesome.

I was using this tool (which seems to work perfectly to gather coverage) but when I triggered the reporting tool, it tried to write a very a file with a long filename. (Probably something related with requests to NewRelic).

screen shot 2016-09-14 at 10 19 22
## Here's what I've done (history of steps and commands):
1. Installed the older version (chromium).
2. Loaded your extension
3. Accessed https://www.cheaptickets.nl (I know the load is terribly slow, we're working on it 😄 )
4. Clicked on `get coveragez`
5. When the page ended loading, I clicked on the `Copy Report Info to clipboard`
6. `$ pbpaste > ~/ctnl.coverage`
7. `$ node gen_report.js ~/ctnl.coverage`
8. Error above is thrown.

I assume truncating the file's name would be enough I guess, will try to come up with a PR for this, if not needed just say so :)

### PR DESCRIPTION
**Pull request by mAiNiNfEcTiOn**
# What does this PR do:

Basically adds an 'interceptor' that verifies if the filepath being written is within 255 chars long. If not, will get the difference and remove the number of characters == difference from the baseName of the file.

Fixes #1 
# Where should the reviewer start:
- Diffs
- You can check issue #1 and try the same thing with `master`and with this PR.

### CODE REVIEW

File: reporter/gen_report.js [hunk 1]
```diff
@@ -32,11 +35,22 @@ Object.keys(originals).forEach(key => {
       escape(atob(originals[key]))));
 });
 
+var fileWriter = new FileWriter(false);
+
+fileWriter.writeFile = function writeFile(file, callback) {
+  if (file.length > 255) {
+    var excess = file.length - 255;
+    var baseName = path.basename(file, '.html')
```
Comment (samccone) [inline reporter/gen_report.js]: I am not sure but does fileWriter write more than just html files?

File: reporter/gen_report.js [hunk 2]
```diff
@@ -32,11 +35,22 @@ Object.keys(originals).forEach(key => {
       escape(atob(originals[key]))));
 });
 
+var fileWriter = new FileWriter(false);
+
+fileWriter.writeFile = function writeFile(file, callback) {
+  if (file.length > 255) {
```
Comment (samccone) [inline reporter/gen_report.js]: I also think most of this logic could be replace w/ a `.slice(0, 255)` approach...

thoughts?

**Comment by samccone** [comment]
thx for the PR, comments left on the diff.

File: reporter/gen_report.js (hunk 1 above)
Comment (mAiNiNfEcTiOn) [reply reporter/gen_report.js]: Yes, it also writes the base.css files from the report, png's etc (see screenshot below):

screen shot 2016-09-14 at 17 36 32

Comment (mAiNiNfEcTiOn) [reply reporter/gen_report.js]: But those normally don't hit the 255 chars length, but I can also use the `path.extname()`.

Will do.

File: reporter/gen_report.js (hunk 2 above)
Comment (mAiNiNfEcTiOn) [reply reporter/gen_report.js]: Well the way I see we have 2 cases:
1. The case were the full path doesn't take more than 255 (which don't need slice)
2. The ones that do need slice...

Then in `the ones that do need slice`, my logic was to remove the excess from the path's basename without the extension. But I believe it can be more performant if we get the extension and do a slice - the length of the extension (and then join it with the extension).

Will revisit it.

**Comment by mAiNiNfEcTiOn** [comment]
Thanks for the comments. Do you see any more places where I can improve it?

**Comment by mAiNiNfEcTiOn** [comment]
Also for a little bit more info:

## Before improvements:

`node gen_report.js ~/ctnl.coverage  2.60s user 0.30s system 101% cpu 2.860 total`

## After improvements:

`node gen_report.js ~/ctnl.coverage  2.38s user 0.29s system 102% cpu 2.615 total`

I guess it's always good to know :)

**Comment by samccone** [comment]
Looks great now much simpler :)

thanks a ton @mAiNiNfEcTiOn :clap:

**Comment by mAiNiNfEcTiOn** [comment]
My pleasure ;)

**Comment by samccone** [comment]
Looks like #3 started happening due to this :)

File: reporter/gen_report.js [hunk 3]
```diff
@@ -32,11 +35,19 @@ Object.keys(originals).forEach(key => {
       escape(atob(originals[key]))));
 });
 
+var fileWriter = new FileWriter(false);
+
+fileWriter.writeFile = function writeFile(file, callback) {
+  var ext = path.extname(file);
+  file = file.slice(0, 255 - ext.length) + ext;
```
Comment (samccone) [inline reporter/gen_report.js:42]: this + ext should only happen if the length was > 255
see #3
